debug: true
web:
  host: 127.0.0.1
  port: 8000
sentry:
  dsn:
  env: dev

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=

database:
  host: localhost
  port: 5432
  user: gameadmin
  password: 123
  database: gamedatabase

bot:
  tg:
    token: 6078553823:AAF2xgT7Gqbtif7KWcREOkjJH7nzfmY3ILE