debug: true
web:
  host: 127.0.0.1
  port: 8000
sentry:
  dsn:
  env: dev

store: {}

database:
  host: localhost
  port: 5432
  user: gameadmin
  password: 123
  database: gamedatabase

bot:
  tg:
    token: 6078553823:AAF2xgT7Gqbtif7KWcREOkjJH7nzfmY3ILE