[tool.black]
line-length = 80
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | migrations

)/
'''