"""updated models to new version

Revision ID: f64de74caf48
Revises: d5aefcda9130
Create Date: 2023-03-28 04:15:46.164009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f64de74caf48'
down_revision = 'd5aefcda9130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.Integer(), nullable=False))
    op.drop_constraint('answers_question_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'question', ['question_id'], ['id'], ondelete='cascade')
    op.drop_column('answers', 'question')
    op.add_column('game', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('remaining_questions', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_constraint('game_winner_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'player', ['winner_id'], ['tg_id'], ondelete='cascade')
    op.drop_column('game', 'winner')
    op.drop_column('game', 'RemainingQuestions')
    op.add_column('gamescore', sa.Column('player_id', sa.BigInteger(), nullable=False))
    op.add_column('gamescore', sa.Column('game_id', sa.Integer(), nullable=False))
    op.drop_constraint('gamescore_player_fkey', 'gamescore', type_='foreignkey')
    op.drop_constraint('gamescore_game_fkey', 'gamescore', type_='foreignkey')
    op.create_foreign_key(None, 'gamescore', 'player', ['player_id'], ['tg_id'], ondelete='cascade')
    op.create_foreign_key(None, 'gamescore', 'game', ['game_id'], ['id'], ondelete='cascade')
    op.drop_column('gamescore', 'game')
    op.drop_column('gamescore', 'player')
    op.add_column('player', sa.Column('games_count', sa.Integer(), nullable=False))
    op.add_column('player', sa.Column('win_count', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'player', ['tg_id'])
    op.add_column('question', sa.Column('theme_id', sa.Integer(), nullable=False))
    op.drop_constraint('question_theme_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'theme', ['theme_id'], ['id'], ondelete='cascade')
    op.drop_column('question', 'theme')
    op.add_column('questionpack', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.drop_constraint('questionpack_admin_fkey', 'questionpack', type_='foreignkey')
    op.create_foreign_key(None, 'questionpack', 'admin', ['admin_id'], ['id'], ondelete='cascade')
    op.drop_column('questionpack', 'admin')
    op.add_column('round', sa.Column('pack_id', sa.Integer(), nullable=False))
    op.drop_constraint('round_pack_fkey', 'round', type_='foreignkey')
    op.create_foreign_key(None, 'round', 'questionpack', ['pack_id'], ['id'], ondelete='cascade')
    op.drop_column('round', 'pack')
    op.add_column('theme', sa.Column('round_id', sa.Integer(), nullable=False))
    op.drop_constraint('theme_round_fkey', 'theme', type_='foreignkey')
    op.create_foreign_key(None, 'theme', 'round', ['round_id'], ['id'], ondelete='cascade')
    op.drop_column('theme', 'round')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'theme', type_='foreignkey')
    op.create_foreign_key('theme_round_fkey', 'theme', 'round', ['round'], ['id'], ondelete='CASCADE')
    op.drop_column('theme', 'round_id')
    op.add_column('round', sa.Column('pack', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'round', type_='foreignkey')
    op.create_foreign_key('round_pack_fkey', 'round', 'questionpack', ['pack'], ['id'], ondelete='CASCADE')
    op.drop_column('round', 'pack_id')
    op.add_column('questionpack', sa.Column('admin', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questionpack', type_='foreignkey')
    op.create_foreign_key('questionpack_admin_fkey', 'questionpack', 'admin', ['admin'], ['id'], ondelete='CASCADE')
    op.drop_column('questionpack', 'admin_id')
    op.add_column('question', sa.Column('theme', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_theme_fkey', 'question', 'theme', ['theme'], ['id'], ondelete='CASCADE')
    op.drop_column('question', 'theme_id')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('player', 'win_count')
    op.drop_column('player', 'games_count')
    op.add_column('gamescore', sa.Column('player', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('gamescore', sa.Column('game', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gamescore', type_='foreignkey')
    op.drop_constraint(None, 'gamescore', type_='foreignkey')
    op.create_foreign_key('gamescore_game_fkey', 'gamescore', 'game', ['game'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('gamescore_player_fkey', 'gamescore', 'player', ['player'], ['tg_id'], ondelete='CASCADE')
    op.drop_column('gamescore', 'game_id')
    op.drop_column('gamescore', 'player_id')
    op.add_column('game', sa.Column('RemainingQuestions', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('winner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_winner_fkey', 'game', 'admin', ['winner'], ['id'], ondelete='CASCADE')
    op.drop_column('game', 'remaining_questions')
    op.drop_column('game', 'winner_id')
    op.add_column('answers', sa.Column('question', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_question_fkey', 'answers', 'question', ['question'], ['id'], ondelete='CASCADE')
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###
